/**
 * Generates `public/robots.txt` and `public/sitemap.xml` from the real blog data.
 * Runs automatically before `vite build` (see package.json -> prebuild).
 *
 * Deriving both files from `src/lib/seo.ts` + `src/data/blog.ts` means the
 * sitemap can never drift from the pages that actually exist.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/** Pulls SITE_URL out of src/lib/seo.ts: one source of truth for all SEO. */
function readSiteUrl() {
  const source = readFileSync(resolve(ROOT, "src/lib/seo.ts"), "utf8");
  const match = source.match(/export const SITE_URL\s*=\s*"([^"]+)"/);
  if (!match) throw new Error("Could not read SITE_URL from src/lib/seo.ts");
  return match[1].replace(/\/+$/, "");
}

/**
 * Slug -> newest ISO date, parsed straight from src/data/blog.ts.
 * Slugs repeat once per language, so only the latest date is kept.
 */
function readPosts() {
  const source = readFileSync(resolve(ROOT, "src/data/blog.ts"), "utf8");
  const latest = new Map();
  const pattern = /slug:\s*"([^"]+)"[\s\S]*?publishedAt:\s*"(\d{4}-\d{2}-\d{2})"/g;
  let match;
  while ((match = pattern.exec(source)) !== null) {
    const [, slug, publishedAt] = match;
    if (!latest.has(slug) || publishedAt > latest.get(slug)) latest.set(slug, publishedAt);
  }
  return [...latest].map(([slug, publishedAt]) => ({ slug, publishedAt }));
}

const SITE_URL = readSiteUrl();
const LANGS = ["fr", "en", "es", "ar", "tam"];
const HREFLANG = { fr: "fr", en: "en", es: "es", ar: "ar", tam: "zgh" };
const TODAY = new Date().toISOString().slice(0, 10);

const posts = readPosts();
const url = (lang, path = "") => `${SITE_URL}/${lang}${path}`;
const escapeXml = (value) =>
  value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

/* ------------------------------- sitemap ------------------------------- */

/** hreflang cluster: the same page in every language, plus x-default. */
function alternates(path) {
  const links = LANGS.map(
    (code) =>
      `    <xhtml:link rel="alternate" hreflang="${HREFLANG[code]}" href="${escapeXml(url(code, path))}"/>`,
  );
  links.push(
    `    <xhtml:link rel="alternate" hreflang="x-default" href="${escapeXml(url("fr", path))}"/>`,
  );
  return links.join("\n");
}

function entry({ loc, path, lastmod, priority, changefreq }) {
  return [
    "  <url>",
    `    <loc>${escapeXml(loc)}</loc>`,
    `    <lastmod>${lastmod}</lastmod>`,
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority}</priority>`,
    alternates(path),
    "  </url>",
  ].join("\n");
}

const urls = [
  ...LANGS.map((lang) => ({
    loc: url(lang),
    path: "",
    lastmod: TODAY,
    changefreq: "weekly",
    priority: "1.0",
  })),
  ...LANGS.map((lang) => ({
    loc: url(lang, "/blog"),
    path: "/blog",
    lastmod: TODAY,
    changefreq: "weekly",
    priority: "0.8",
  })),
  ...LANGS.flatMap((lang) =>
    posts.map(({ slug, publishedAt }) => ({
      loc: url(lang, `/blog/${slug}`),
      path: `/blog/${slug}`,
      // Never advertise a future publication date to crawlers.
      lastmod: publishedAt > TODAY ? TODAY : publishedAt,
      changefreq: "monthly",
      priority: "0.7",
    })),
  ),
];

const sitemap = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
  '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
  ...urls.map(entry),
  "</urlset>",
  "",
].join("\n");

writeFileSync(resolve(ROOT, "public/sitemap.xml"), sitemap, "utf8");

/* ------------------------------- robots -------------------------------- */

const robots = `# https://www.robotstxt.org/robotstxt.html
# Generated by scripts/generate-seo.mjs - edit that file, not this one.

User-agent: *
Allow: /

# AI crawlers are welcome: this is public portfolio and technical content.
User-agent: GPTBot
Allow: /
User-agent: Google-Extended
Allow: /
User-agent: PerplexityBot
Allow: /
User-agent: ClaudeBot
Allow: /

# SEO crawlers get no ranking benefit and only burn crawl budget.
User-agent: AhrefsBot
Disallow: /
User-agent: SemrushBot
Disallow: /
User-agent: DotBot
Disallow: /
User-agent: MJ12bot
Disallow: /

Host: ${SITE_URL.replace(/^https?:\/\//, "")}
Sitemap: ${SITE_URL}/sitemap.xml
`;

writeFileSync(resolve(ROOT, "public/robots.txt"), robots, "utf8");

/* --------------------------- index.html sync --------------------------- */

/**
 * Rewrites every self-referencing URL in index.html to SITE_URL.
 * This is what stops canonical / og:url / og:image / JSON-LD from drifting
 * away from the sitemap (they pointed at github.io while the site ran on Vercel).
 */
const INDEX = resolve(ROOT, "index.html");
const LEGACY_URLS = [
  "https://BOU-FOUSMOHAMED.github.io/my_owen_profile",
  "https://my-portfolio.vercel.app",
  "https://my-ownprofile.vercel.app",
  "https://boufousmohamed.vercel.app",
];

const before = readFileSync(INDEX, "utf8");
let index = before;
for (const legacy of LEGACY_URLS) {
  if (legacy !== SITE_URL) index = index.split(legacy).join(SITE_URL);
}

/**
 * Icon links are normalised here rather than trusted in the markup:
 * every href must stay absolute (a relative one 404s on /fr/blog/<post>),
 * and the SVG declaration must point at the .svg, never at the .webp —
 * a MIME mismatch browsers silently ignore. Kept in sync with
 * public/manifest.webmanifest.
 */
const ICON_LINKS = [
  '    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />',
  '    <link rel="icon" type="image/webp" href="/profile.webp" />',
  '    <link rel="apple-touch-icon" href="/profile.webp" />',
  '    <link rel="manifest" href="/manifest.webmanifest" />',
];

const ICON_RE = /[ \t]*<link rel="(?:icon|apple-touch-icon|manifest)"[^>]*>[ \t]*\r?\n?/g;
index = index.replace(ICON_RE, "");

// Collapse the blank lines the removal left behind, so repeated builds converge.
index = index.replace(/\n{3,}/g, "\n\n");

const OG_ANCHOR = /(\n)([ \t]*)(<meta property="og:type")/;
if (!OG_ANCHOR.test(index)) {
  throw new Error('index.html: no <meta property="og:type"> anchor - cannot place icon links');
}
index = index.replace(OG_ANCHOR, (_, nl, indent, meta) => `${nl}${ICON_LINKS.join(nl)}${nl}${nl}${indent}${meta}`);

if (index === before) {
  console.log("[seo] index.html already in sync");
} else {
  // Safety net: sameAs links (GitHub, LinkedIn) must never be rewritten.
  if (/https:\/\/(github\.com|www\.linkedin\.com)/.test(index) === false) {
    throw new Error("index.html rewrite dropped a sameAs link - aborting");
  }
  writeFileSync(INDEX, index, "utf8");
  console.log("[seo] index.html self-referencing URLs + icon links synced to SITE_URL");
}

console.log(
  `[seo] robots.txt + sitemap.xml written: ${urls.length} URLs (${posts.length} posts x ${LANGS.length} langs) -> ${SITE_URL}`,
);